server:
  port: 6001
spring:
  application:
    name: zipkin
  boot:
    admin:
      client:
        api-path: http://192.168.47.131:4001
  cloud:
    config:
      # master 分支
      label: master
      #配置文件名称
      name: zipkin
      #激活配置
      profile: prod
      #配置中心地址
      uri: 192.168.47.131:3001
eureka:
  instance:
    hostname: 192.168.47.131
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.47.131:8761/eureka
#不配置会报错
management:
  metrics:
    web:
      server:
        auto-time-requests: false





